name: doctor_ui
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  get: 4.6.6
  flutter_slider_drawer: ^2.1.3
  day_picker: ^2.2.0
  weekday_selector: ^1.1.0
  weekly_date_picker: ^1.4.2
  flutter: 
    sdk: flutter
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  firebase_database: ^10.5.4

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - asset/image/


