// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeHWIF4wCKVoZJmOsIJmw_psi88A0VmYw',
    appId: '1:213930037996:web:4b2a05a5afdc46ca970bc9',
    messagingSenderId: '213930037996',
    projectId: 'clinic-e0e4d',
    authDomain: 'clinic-e0e4d.firebaseapp.com',
    storageBucket: 'clinic-e0e4d.appspot.com',
    measurementId: 'G-91P93QBSXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQS2FD5uHSAidUQua0EyJ43ET2yW1iw-0',
    appId: '1:213930037996:android:781b913c9ceec79e970bc9',
    messagingSenderId: '213930037996',
    projectId: 'clinic-e0e4d',
    storageBucket: 'clinic-e0e4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyGbWHYwPtUtrmUCEWnOxDPg8SgVkAqYc',
    appId: '1:213930037996:ios:939584201420e29a970bc9',
    messagingSenderId: '213930037996',
    projectId: 'clinic-e0e4d',
    storageBucket: 'clinic-e0e4d.appspot.com',
    iosBundleId: 'com.example.doctorUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyGbWHYwPtUtrmUCEWnOxDPg8SgVkAqYc',
    appId: '1:213930037996:ios:939584201420e29a970bc9',
    messagingSenderId: '213930037996',
    projectId: 'clinic-e0e4d',
    storageBucket: 'clinic-e0e4d.appspot.com',
    iosBundleId: 'com.example.doctorUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeHWIF4wCKVoZJmOsIJmw_psi88A0VmYw',
    appId: '1:213930037996:web:f7e00fa562bb3fad970bc9',
    messagingSenderId: '213930037996',
    projectId: 'clinic-e0e4d',
    authDomain: 'clinic-e0e4d.firebaseapp.com',
    storageBucket: 'clinic-e0e4d.appspot.com',
    measurementId: 'G-8S11G8Y23N',
  );
}
